### ISSUE TITLE
Set weights on paths

### ISSUE THREAD

**Issue by ahcox** [getgrav/grav-plugin-sitemap#11]
Hi,

For wordpress, yoast's SEO plugin will set weights on different pages in the sitemap according to some automatic rules. That would be good.

In addition, setting weights manually would also be useful. Random example: you make a website selling something so you want the front page and the key features pages to have 0.9 to 1.0 weight and things like blog posts to have < 0.5 weight so google lists things you want people to click on higher in results pages even if it is just for the search "site:mysite.com".

**Comment by NeonTigerWeb** [comment]
I thought this was included already?

**Comment by flaviocopes** [comment]
Per-page priority can be set. The plugin config could have a list of defaults, agree.

**Comment by sebastianbaumann** [comment]
How can this be done?
