### ISSUE TITLE
Validation failed: Invalid input in "Sitemap Priority"

### ISSUE THREAD

**Issue by madelyncruz** [getgrav/grav-plugin-sitemap#13]
On each page, I've set the sitemap "Priority" and "Frequency". I've hit save and the changes applied. When I'm trying to edit the page in "Expert" mode, an error message comes up "Validation failed: Invalid input in "Sitemap Priority", but it works OK with the "Normal" mode.

**Comment by flaviocopes** [comment]
I pushed a PR that should solve this: https://github.com/getgrav/grav-plugin-sitemap/pull/14/files 

Can you try applying those changes? Now the value should save as 

```yaml
sitemap:
    priority: '0.5'
```

when in normal mode, and save fine in expert mode.

**Comment by madelyncruz** [comment]
I've applied the changes given in the link above and all are working fine now. Thank you.
