### ISSUE TITLE
Allow using dot "." in sitemap route

### ISSUE THREAD

**Issue by martinsik** [getgrav/grav-plugin-sitemap#17]
[Regular expression](https://github.com/getgrav/grav-plugin-sitemap/blob/develop/blueprints.yaml#L33) that checks valid sitemap route doesn't allow using "." characters so I can't use route like `/sitemap.xml` which is I think more common than `/sitemap`.

**Comment by flaviocopes** [comment]
You cannot have `/sitemap.xml` as the route. The route must be `/sitemap`, `.xml` is the page format, which is already xml. 
This means `sitemap` and `sitemap.xml` point to the same page.

If you want to deny access to `sitemap` and just allow sitemap.xml, you can do that via .htaccess, if you want.

**Comment by danreb** [comment]
@martinsik you don't need to put sitemap.xml in the route, it is already accessible in that URL. you can then just make the sitemap redirect to sitemap.xml in .htaccess using a very simple rule

```
Redirect 301 /sitemap /sitemap.xml
```

this is what i've done.

Regards,
Danreb

**Comment by martinsik** [comment]
Thanks, I guess it's all right then. I didn't expect I can use both `/sitemap` and `/sitemap.xml` so I was confused when the validation didn't allow me to use `/sitemap.xml`.
