### ISSUE TITLE
Closing </head> tag in header invalidating xml format

### ISSUE THREAD

**Issue by pbwebdev** [getgrav/grav-plugin-sitemap#18]
Strange additional </head> in output of code causing Google Search console not to recognise the sitemap as valid xml.

https://weoutsource.com.au/sitemap

![screen shot 2016-03-03 at 10 31 45 am](https://cloud.githubusercontent.com/assets/3688954/13479479/47527e1c-e12b-11e5-8533-24ed65f6f2d3.png)

**Comment by rhukster** [comment]
Not sure where it's coming from. 

Not in our output that I can see: https://github.com/getgrav/grav-plugin-sitemap/blob/develop/templates/sitemap.xml.twig

**Comment by eilyk** [comment]
Take a look at this article, for me it's ok 
https://developers.google.com/speed/pagespeed/module/filter-head-add#configuration

**Comment by BugHunter2k** [comment]
Same here. 
Grav 1.0.10 with plugin 1.6.0 (custom theme) 
Sitemap: https://www.judo-rietberg.de/sitemap

**Comment by flaviocopes** [comment]
Just tried, not happening for me on Grav 1.0.10 and Sitemap 1.6.0: https://gravshoppingcart.com/sitemap really strange

**Comment by BugHunter2k** [comment]
when I append .xml there is no head tag included
https://www.judo-rietberg.de/sitemap.xml

**Comment by rhukster** [comment]
Can't recreate this i'm afraid. Closing for now.  Please open up again if the issue reoccurs.
