### ISSUE TITLE
Add tag-pages to sitemap

### ISSUE THREAD

**Issue by K232** [getgrav/grav-plugin-sitemap#2]
I'm no sitemap- or SEO-expert but I guess it would make sense to also add the dynamically created pages like http://getgrav.org/blog/tag:phpstorm into the sitemap so they could be found by search engines easier?

**Comment by rhukster** [comment]
This is not a trivial thing to add. To Grav a page with a tag is not an actual page, it's simply the blog page with some filtering.  The sitemap plugin would have to get the specific content of that page with the filtering and add that to the sitemap.  Very tricky and a lot of overhead. This is not something that we are going to be able to add to the sitemap plugin.
