### ISSUE TITLE
Sitemap plugin shall honor grav page header flag visible

### ISSUE THREAD

**Issue by trial-n-error** [getgrav/grav-plugin-sitemap#21]
Hi,

the sitemap plugin lists also invisible pages. Pages with the header "visible: false" probably should not be listed. They might be ignored by sitemap plugin configuration though.

Fix seems rather simple.

Best regards,
 Mario

**Comment by flaviocopes** [comment]
"Not visible" means the page is not in the navigation https://learn.getgrav.org/content/headers#visible. But still, that page should be listed in the sitemap, as part of the site.

To remove a page from the site and from the sitemap you need to set it as `published: false`
