### ISSUE TITLE
Better look & different structure (sitemaps for taxonomys)

### ISSUE THREAD

**Issue by danielpetrica** [getgrav/grav-plugin-sitemap#23]
- Is there any way to change the look of the sitemap? 
output on new line will be enough
- Can we have a different sitemap structure and divide sitemap in smaller parts
example (related to one website i'm building): 
sitemap index 
 |-themes
 |-authors
 |-quotes (one page with x lines)

**Comment by rhukster** [comment]
The sitemap basically just outputs the same way as the menu would.. By that I mean it just recreates the structure of the page folders.  It outputs as XHTML, but you can override the output potentially by copying the `sitemap.xml.twig` from the plugin's `templates/` folder into your theme's `templates/` folder and modifying it.
