### ISSUE TITLE
Extra spaces

### ISSUE THREAD

**Issue by mafisz** [getgrav/grav-plugin-sitemap#27]
I've got error:

```
>   <?xml version="1.0" encoding="UTF-8"?>
> --^
```

Someone have idea from where this two spaces may come?

**Comment by flaviocopes** [comment]
I saw the same issue yesterday with the theme main PHP file (`user/themes/mytheme/mytheme.php`) having trailing spaces after the closing PHP tag. Could it be the same issue?

**Comment by mafisz** [comment]
Thanks :)
I copy code from [grav documentation](https://learn.getgrav.org/themes/customization) and there was two extra spaces after closing tag
`<?php
 namespace Grav\Theme;

 class Mytheme extends Antimatter
 {
     // Some new methods, properties etc.
 }
?>  `

**Comment by flaviocopes** [comment]
Ah thanks for mentioning, I fixed the example
