### ISSUE TITLE
Default route

### ISSUE THREAD

**Issue by DonD01** [getgrav/grav-plugin-sitemap#29]
The plugin probably should use a page's default route, for example `/` not `/home`

**Comment by flaviocopes** [comment]
Related to https://github.com/getgrav/grav-plugin-sitemap/pull/28

**Comment by simonhaenisch** [comment]
+1

**Comment by antonspavlovs** [comment]
+1

**Comment by lukasfrei** [comment]
+1

**Comment by flaviocopes** [comment]
Fixed in https://github.com/getgrav/grav-plugin-sitemap/pull/28
