### ISSUE TITLE
Invisible Tab on custom page blueprints

### ISSUE THREAD

**Issue by JohannMakitrin** [getgrav/grav-plugin-sitemap#30]
Hi,

thanks for the plugin!

It seems that the plugin adds an invisible tab on custom page blueprints.

![2017-02-15 15_53_53-bearbeiten prostituierte _ erotikum prostschg](https://cloud.githubusercontent.com/assets/25499744/22979649/639162e4-f397-11e6-99e8-d49749699ebb.png)

**Comment by flaviocopes** [comment]
Yes the plugin currently assumes there is an "Options" tab, as defined in the Default blueprint: https://github.com/getgrav/grav/blob/develop/system/blueprints/pages/default.yaml#L38-L41

Add it to your custom blueprint that does not extend Default, and you should be ok.

**Comment by JohannMakitrin** [comment]
Thank you @flaviocopes !
