### ISSUE TITLE
Changefrequency float validation error

### ISSUE THREAD

**Issue by DavideTriso** [getgrav/grav-plugin-sitemap#31]
Setting the changefrequency to 1 causes an error:

"cannot resolve a node with !&lt;tag:yaml.org,2002:float&gt; explicit tag at line ..., column ...: priority: !!float 1"

```
sitemap:
    changefreq: yearly
    priority: !!float 1
```

**Comment by flaviocopes** [comment]
Weird, seems that YAML is claiming something is wrong in the format, but I cannot replicate the problem.

**Comment by DavideTriso** [comment]
The error appears every time I set 'changefreq' to 1 in the admin plugin.
I have made some tests and changing the validation type to 'number' for 'header.sitemap.priority' in the blueprint sitemap.yaml  seems to solve the problem.

**Comment by flaviocopes** [comment]
Cannot replicate. If anyone else stumbles on this, comment here
