### ISSUE TITLE
Call to undefined method Grav\Common\Page\Page::canonical()

### ISSUE THREAD

**Issue by aureolacodes** [getgrav/grav-plugin-sitemap#44]
After enabling the plugin I get an error on the /sitemap page. I think the name of the method has changed in the most recent version of grav. Now you need to call **routeCanonical** instead. For backwards compatibility you might want to check if **canonical** or **routeCanonical** exists.

![bildschirmfoto 2017-05-15 um 12 08 02](https://cloud.githubusercontent.com/assets/16824279/26053017/8d0c6ed2-3967-11e7-8059-d0e3c5ea4607.png)

Cheers, Chris

**Comment by aureolacodes** [comment]
Just checked my grav version... actually its the other way around. The method was called **routeCanonical** before and now its **canonical**. So I think the error will be fixed when I upgrade my grav installation.

**Comment by flaviocopes** [comment]
Yes, a recent addition to the plugin is using a method that was introduced just recently (4 months ago) in Grav. Updating Grav will fix it.
