### ISSUE TITLE
Different behaviour/display in different system for sitemap output

### ISSUE THREAD

**Issue by kumaravel29** [getgrav/grav-plugin-sitemap#45]
I have using the GRAV module in my local Windows machine and on a linux server using the XAMPP.
I have also installed the sitemap plugin on both system and both the system have been kept in sync.
And I have made a small change in the plugin - 
   1. Commented the sorting line in the sitemap.php (ksort($routes);  --> line 64)
   2. Changed the line 75 in sitemap.php from '$entry->location = $page->canonical();'  --->   '$entry->location = $this->grav['base_url_relative'] . $page->routecanonical();'

The output of these changes are completely different in both the system.
Can you please help me out in this as this has a dependency in my requirement and want it to be in proper order.

Thanks in advance

Regards,
Kumaravel

**Comment by flaviocopes** [comment]
We cannot really support customized versions of the plugin. Why should you change that?

**Comment by Kumaravel2904** [comment]
I am storing some medias like images and videos and want to retreive it in the same order in which I have saved or as per the numeric prefix.
The plugin was actually sorting it based on the folder name, so had to make the mentioned minor changes.
