### ISSUE TITLE
Support for SSL

### ISSUE THREAD

**Issue by jrivero** [getgrav/grav-plugin-sitemap#46]
The generated urls for the sitemap when the site is ssl not have https. The "force_ssl" setting has no effect.

**Comment by conradfr** [comment]
+1

**Comment by flaviocopes** [comment]
HTTPS should be used if $_SERVER['HTTPS'] is true on the server. Enforcing https via htaccess (on Apache) should work: https://stackoverflow.com/questions/4398951/force-ssl-https-using-htaccess-and-mod-rewrite

**Comment by conradfr** [comment]
Well my host use $_SERVER["HTTP_HTTPS"] instead of  _SERVER["HTTP_HTTPS"], I think it depends on the Apache version.

**Comment by flaviocopes** [comment]
Oh, I read about it, that looks like an issue with Nginx. Are you using Nginx?

**Comment by flaviocopes** [comment]
(related issue https://forge.typo3.org/issues/32341)

**Comment by jrivero** [comment]
I use nginx and the set of *HTTPS* header to *on* has solutionated the problem. Thanks!

**Comment by iamchristopher** [comment]
I see a workaround posted here, but is there word on an official fix?
