### ISSUE TITLE
(Auto)Ignore external Links

### ISSUE THREAD

**Issue by ciscllc** [getgrav/grav-plugin-sitemap#47]
Hi,

would be great to (auto)exclude external links as it may be a problem with searchengines (will become invalid) - with external links I mean www.mysite.com is the main site and www.google.com is an external link / URL

https://productforums.google.com/forum/#!topic/webmasters/zDCMIOHZBgU;context-place=topicsearchin/webmasters/authorid$3AAPn2wQdYSQNTGlByz1-QOv-Py6U_jV9D7JF1wTOnWzTqSWU3P9A5ECifpzHnTh6e6krJOBLNEOv-%7Csort:date%7Cspell:false

Or even to have a checkbox at the pages level.

**Comment by rhukster** [comment]
Fixed for next release
