### ISSUE TITLE
Ignores - question

### ISSUE THREAD

**Issue by bdillahu** [getgrav/grav-plugin-sitemap#5]
I'm unclear how the ignores works... I have some folders of content named _09.defunct_pages - non-routable. Sitemap still includes it, so I have tried

ignores:
  - /_09.defunct_pages
  - /_09.defunct_pages/*

and other combinations to no avail... 

Ideas?

Thanks!

**Comment by rhukster** [comment]
you have to put the route, so that's the part that you see in your browser when you go to the page. So if your URL is `http://yoursite.com/some/path/to/page` then the route would be `/some/path/to/page`

**Comment by bdillahu** [comment]
Sorry, haven't been able to get back to this piece of the project for a bit.

It does work as you say (obviously), but I'll point out that (maybe expected) it apparently doesn't take wildcards or suppress the entire "tree" if you have nested pages.

I have (all directories):

- rss_link_items
    - item1
    - item2
    - item3

This works great:

ignores:
  - rss_link_items/item1  

These don't seem to (trying to ignore the entire branch of the tree:

ignores: 
  - rss_link_items/*
  - rss_link_items


Thanks!

**Comment by karfau** [comment]
@bdillahu in case you have not seen it: this is supported now but the wildcard need to be `.*`.

**Comment by bdillahu** [comment]
Thanks for the head's up :-)

-- 
Bruce Dillahunty
http://brucedillahunty.xyz
