### ISSUE TITLE
Redirecting sitemap to home page

### ISSUE THREAD

**Issue by kk6axq** [getgrav/grav-plugin-sitemap#53]
When I load sitemap.xml on my website, it redirects to /, the root. When I try to load it again in a browser, it works, but Google Webmaster is having problems locating the xml as it gets redirected to the home page. How can I fix this?

**Comment by rhukster** [comment]
I can't replicate this :(

**Comment by kk6axq** [comment]
The sitemap loads correctly here http://www.northernazaerialphotography.com/sitemap, but when fetching the raw xml one here: http://www.northernazaerialphotography.com/sitemap.xml it redirects to the website root.
