### ISSUE TITLE
Warning: Resource interpreted as Stylesheet but transferred with MIME type application/xml

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-sitemap#55]
In Chrome dev tools I get the following warning:
> Resource interpreted as Stylesheet but transferred with MIME type application/xml: "https://mydomain/user/plugins/sitemap/sitemap.xsl".

It is about line 2 in the generated sitemap:
`<?xml-stylesheet type="text/xsl" href="/user/plugins/sitemap/sitemap.xsl"?>`

**Comment by glasswork** [comment]
Possibly related: Google throws error on the sitemap saying that is an html page not xml and gives line 2 as the culprit. Let me know if I should open as separate issue. Could a config option be added to not have the xsl included? After all, the xml file is human readable enough as is. My previous sitemap did not include any
![screen shot 2018-08-20 at 7 39 54 am](https://user-images.githubusercontent.com/4681577/44343914-7c056c00-a44c-11e8-872d-42a3ac9a8f86.png)
 xsl declaration and had no errors.

**Comment by rhukster** [comment]
I don't see this, i think it's been addressed already
