### ISSUE TITLE
Shows protected page structure that requires users to login to view

### ISSUE THREAD

**Issue by Dean-kasail** [getgrav/grav-plugin-sitemap#62]

**Comment by rhukster** [comment]
A work around is that you can set:

```
sitemap:
    ignore: true
```

On pages you don't want to show up.

**Comment by rhukster** [comment]
Or add them to the ignore list in the plugin configuration.

**Comment by rhukster** [comment]
I've added a new "Ignore Protected Pages" option in sitemap 2.0
