### ISSUE TITLE
Version 1.9.3 appears to not work at all

### ISSUE THREAD

**Issue by Tugzrida** [getgrav/grav-plugin-sitemap#65]
After updating to 1.9.3, going to `/sitemap` or `/sitemap.xml` on my site yields a 404. Tried with a clean install and got the same result.

The debugger doesn't seem to show on 404 responses, so I'm not sure where else to start looking for issues.

**Comment by rhukster** [comment]
Hmm. I added the ability for an existing html page to render.  Do you have a /sitemap page in your user/pages/ folder?

**Comment by Tugzrida** [comment]
Nope, just the normal site content.

My clean install was just with the latest Gray + Admin zip, then installing sitemap, which again returned 404. I don’t recall there being any specific configuration when I originally installed sitemap on my main site 🤔

**Comment by rhukster** [comment]
Ok found the issue and fixed it.  Sorry about that, my test site had a manually created `/sitemap` page and this made it work, removing that page caused it to fail.  I have a check for this now.  New release will be available in 15 mins or so.

**Comment by Tugzrida** [comment]
Thank you! All working 😁
