### ISSUE TITLE
Add link rel="sitemap" by default to head of pages

### ISSUE THREAD

**Issue by lazybadger** [getgrav/grav-plugin-sitemap#67]
It's more themes question, but enhancement in order "to be just perfect" for plugin, which can do it automatically
`<link rel="sitemap" type="application/xml" title="Sitemap" href="<site>/sitemap.xml">`

**Comment by rhukster** [comment]
Perhaps an optional thing

**Comment by NicoHood** [comment]
I think this should be part of the theme. However it is a nice addition, thanks for the note!
