### ISSUE TITLE
array_key_exists exception on 1.7-rc10 with Gantry latest

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-sitemap#74]
Installed Sitemap plugin, enabled, browsed to '/sitemap', got the `array_key_exists(): The first argument should be either a string or an integer` error on line 78 of sitemap.php:

```
$lang_available = (empty($page_languages) || array_key_exists($current_lang, $page_languages));
```

**Comment by mahagr** [comment]
FYI: Not related to Grav 1.7 but PHP 7.4.

**Comment by thekenshow** [comment]
This is happening on PHP 7.2.24.

**Comment by mahagr** [comment]
Thanks.

**Comment by mahagr** [comment]
It looks like `$language->getLanguage()` and `$language->getDefault()` can both return null.

CC @rhukster

**Comment by mahagr** [comment]
@thekenshow Workaround is to set (default) language in system.yaml.
