### ISSUE TITLE
External URLs in sitemap

### ISSUE THREAD

**Issue by lazybadger** [getgrav/grav-plugin-sitemap#76]
Folllow-up for #47 

**Some subset** of external links from site, referenced in main page content, may appear in sitemap (with default setting of plugin).
Only one possible correlation is reliably discovered in addition to _old (still open) issue from Jul 2017_:

- Sites on clean Grav core doesn't have external URLs in sitemap, while site with Gantry-based theme got some external URLs in sitemap

Full list of my externals and status of inclusion:

twitter.com/rockettheme
facebook.com/rockettheme
rockettheme.com/product-updates?rss
rockettheme.com/docs/grav/themes/hadron **YES**
rockettheme.com/forum/grav-theme-hadron **YES**
docs.gantry.org/gantry5/particles/logo
rockettheme.com/docs/grav/themes/hadron/demo.md
rockettheme.com/grav/themes/hadron **YES**
chartjs.org/
github.com/nnnick/Chart.js
rockettheme.com/docs/joomla/basic/responsive_support_classes.md
twitter.com/davegandy
learn.getgrav.org/basics/installation
opensource.org/licenses/mit-license.html
fontawesome.io/icons/
docs.gantry.org/gantry5/basics/installation
rockettheme.com/docs/grav/start/rocketlauncher.md
rockettheme.com
w3schools.com/html/html5_canvas.asp
scripts.sil.org/OFL
rockettheme.com/docs/grav/themes/hadron/comingsoon.md

**Comment by nvandelden** [comment]
I can confirm this issue happens with a Gantry based theme.

**Comment by rhukster** [comment]
I've removed the external URLs by default in the upcoming version 2.0 of sitemap.  These are set with `external_url: http://something.com` in the frontmatter.
