### ISSUE TITLE
Correct URL if using slug for pages

### ISSUE THREAD

**Issue by zonehun** [getgrav/grav-plugin-sitemap#80]
First of all thank you for the great plugin! It was super easy to install and it is working. 

My website is using two languages (hu and en). hu is the default and I'm using slugs for the en pages. Now I see both of the languages in the sitemap XML, but the en pages URL is not the ones with slugs. 

Here is the sitemap: http://learn.co3app.com/sitemap

How can I create the sitmap with the correct URL (containing the slug) for the en pages? 

Any help would be appreciated!

**Comment by rhukster** [comment]
Multilang support has been rewritten and significantly improved.  Please try v3.0
