### ISSUE TITLE
HTML tags are added to sitemap.xml

### ISSUE THREAD

**Issue by blijerd** [getgrav/grav-plugin-sitemap#82]
I don't know in which version this issue started; but there are some wrong tags in sitemap.xml; it contains 'html' and 'body' at the start and end

` <?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/user/plugins/sitemap/sitemap.xsl"?><html><body><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
`

<img width="1198" alt="Schermafbeelding 2020-08-09 om 16 20 41" src="https://user-images.githubusercontent.com/47414589/89734468-89aec480-da5c-11ea-84c3-472b1b85b423.png">

**Comment by NicoHood** [comment]
I dont have this issue, how can you reproduce it?

**Comment by rhukster** [comment]
Cannot reproduce.  Most likely the result of some other plugin interferring.
