### ISSUE TITLE
Ignore protected pages does not work

### ISSUE THREAD

**Issue by Japhys** [getgrav/grav-plugin-sitemap#84]
I enabled this option in plugin config. However all my protected pages are listed in de sitemap.xml. The redirect to login page of course but still I like them not to be in there

pages have this code

access:
    site.login: true
    admin.login: true
login:
    visibility_requires_access: true

**Comment by rhukster** [comment]
Actually they should not be displayed with the latest version if you have `ignore_protected: true` because any page that has `access:` will be ignored.
