### ISSUE TITLE
Alternative replacement for ignore:true, using visible or published

### ISSUE THREAD

**Issue by pierrejoye** [getgrav/grav-plugin-sitemap#88]
Good evening,

Thanks you for this handy plugin!

Would it make sense to use either the visible or publish page properties instead of as a default alternative of sitemape: ignore: true?

I was only a little surprised to see unpublished or visible: false pages in the sitemap (I use a few to compose pages as well, include them from twig).

I can provide a PR if desired, to check either of these properties. What do you think?

**Comment by rhukster** [comment]
the page needs to be `routable` and `published` in order for it for it to be reachable by crawlers.  `visible` is just to indicate if the page should be in the menu or not, so it's really not an appropriate setting to use.  I think having a sitemap specific ignore is the best way.
