### ISSUE TITLE
Invalid namespace according to google console

### ISSUE THREAD

**Issue by pierrejoye** [getgrav/grav-plugin-sitemap#89]
![image](https://user-images.githubusercontent.com/282408/105722257-0e809280-5f58-11eb-8722-6d3487ddbc89.png)

According to: https://www.sitemaps.org/protocol.html

it seems that:

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

is the right one.

**Comment by rhukster** [comment]
At least with the latest version in develop branch it passes sitemap validation in 3rd party testing sites I tried.

**Comment by pierrejoye** [comment]
Master is different and works fine :)
