### ISSUE TITLE
Plugin Broken on RC4

### ISSUE THREAD

**Issue by HOFB2015** [getgrav/grav-plugin-sitemap#9]
Hi

After installing RC4 today sitemap.xml loads as 

Whoops \ Exception \ ErrorException (E_WARNING)
in_array() expects parameter 2 to be array, null given

Open: /var/www/houseofbhangra.com/system/src/Grav/Common/Grav.php
 
        /** @var Config $config */
        $config = $this['config'];
 
        $uri_extension = $uri->extension();
 
        // Only allow whitelisted types to fallback
        if (!in_array($uri_extension, $config->get('system.pages.fallback_types'))) {
            return;
        }

I was previously on one of the 0.9 versions..

**Comment by flaviocopes** [comment]
Just tested, works fine! As long as https://github.com/getgrav/grav/blob/develop/system/config/system.yaml#L57 is present (and not overridden in your user/config/system.yaml)

**Comment by hwmaier** [comment]
Maybe 
```
if (!in_array($uri_extension, $config->get('system.pages.fallback_types'))) {
```
needs to change to
```
if (!in_array($uri_extension, $config->get('system.pages.fallback_types', ['png','jpg','jpeg','gif']))) {
```

**Comment by flaviocopes** [comment]
Fixed by https://github.com/getgrav/grav/commit/7f1d3a94fe98e7e56418554b277329d1f4ca6ba9
