### ISSUE TITLE
Problem with a multilanguage sitemap

### ISSUE THREAD

**Issue by Agrasu** [getgrav/grav-plugin-sitemap#94]
I have a problem with generating the sitemap in two language versions.

Now I have two versions in one sitemap, but I need this solution:
- https://website.com/en/sitemap.xml (includes only `/en/` links)
- https://website.com/pl/sitemap.xml (includes only `/pl/` links).

Propably I found an unnecessary(?) line 126 in file `sitemap.php`:
```
$pages->reset();
```
If i remove this line my sitemap is generated fine.

Can you solve the problem this way or another?

**Comment by rhukster** [comment]
Sitemap was not handling multi-language properly before. The sitemap is intended for Google and other bots to get a thorough understanding of your site, so we now follow the Goolge guidelines: https://developers.google.com/search/docs/advanced/crawling/localized-versions

If you were leveraging the sitemap for a visual representation (not for search engines), you can enable the new `html_support` option and this works on a per-language basis like it used to work before: https://github.com/getgrav/grav-plugin-sitemap#html-support
