### ISSUE TITLE
Sitemap blanked out problem

### ISSUE THREAD

**Issue by CaiMiao** [getgrav/grav-plugin-sitemap#97]
Previously it works but not working again.
Confirmed that default settings would still blank.
Page cache via AdvancedPageCache disabled for sitemap.

<https://l10n.346lab.org/sitemap>

Responsed xml content fyi :

![image](https://user-images.githubusercontent.com/4640483/125554827-db396a6c-b4cc-4fb4-8121-4057c0c7f7ca.png)

**Comment by Karmalakas** [comment]
I believe your templates are messed up somehow. That's not a sitemap template in the source.
It looks like the beginning is from `partials/sitemap.xml.twig`, but then the content is from some `...html.twig` (looks like `base.html.twig` or any other full layout). 

By any chance you have a page named also `sitemap` maybe? Just guessing

**Comment by CaiMiao** [comment]
![image](https://user-images.githubusercontent.com/4640483/125585665-b4413753-119f-4fe3-a15f-5810ecdf6047.png)
@Karmalakas nope and nope, i also wonder why it messed.

**Comment by Karmalakas** [comment]
Could you check you theme templates if sitemap is there?

**Comment by CaiMiao** [comment]
> Could you check you theme templates if sitemap is there?

nope.

![image](https://user-images.githubusercontent.com/4640483/125590605-51ae7302-58c5-424d-8e27-f183c05f72bf.png)

**Comment by Karmalakas** [comment]
It's not in `/partials`, but rather in root of `/templates` (I made a mistake earlier 🙂)
How does you Sitemap plugin config look like?

**Comment by CaiMiao** [comment]
> It's not in `/partials`, but rather in root of `/templates` (I made a mistake earlier )
> How does you Sitemap plugin config look like?

@Karmalakas unmodified quark theme, and unmodified default plugin config, ty.

```
# tree -L 2
.
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- assets
|   `-- quark-screenshots.jpg
|-- blueprints
|   |-- blog.yaml
|   |-- default.yaml
|   |-- item.yaml
|   |-- modular
|   `-- partials
|-- blueprints.yaml
|-- css
|   |-- bricklayer.css
|   |-- custom.css
|   `-- line-awesome.min.css
|-- css-compiled
|   |-- spectre-exp.css
|   |-- spectre-exp.min.css
|   |-- spectre-icons.css
|   |-- spectre-icons.min.css
|   |-- spectre.css
|   |-- spectre.min.css
|   |-- theme.css
|   `-- theme.min.css
|-- fonts
|   |-- line-awesome.eot
|   |-- line-awesome.svg
|   |-- line-awesome.ttf
|   |-- line-awesome.woff
|   `-- line-awesome.woff2
|-- gulpfile.js
|-- images
|   |-- favicon.png
|   |-- grav-logo.svg
|   `-- logo
|-- js
|   |-- bricklayer.min.js
|   |-- jquery.treemenu.js
|   |-- scopedQuerySelectorShim.min.js
|   |-- singlepagenav.min.js
|   |-- site.js
|   `-- smooth-scroll.min.js
|-- languages.yaml
|-- package.json
|-- quark.php
|-- quark.yaml
|-- screenshot.jpg
|-- scss
|   |-- spectre
|   |-- spectre-exp.scss
|   |-- spectre-icons.scss
|   |-- spectre.scss
|   |-- theme
|   `-- theme.scss
|-- templates
|   |-- blocks
|   |-- blog.html.twig
|   |-- default.html.twig
|   |-- error.html.twig
|   |-- forms
|   |-- item.html.twig
|   |-- macros
|   |-- modular
|   |-- modular.html.twig
|   `-- partials
`-- thumbnail.jpg
```

**Comment by Karmalakas** [comment]
I'm out of ideas. But I'm pretty sure it's something with your setup. Maybe some other plugin messes up something (you could try disabling one by one)

**Comment by CaiMiao** [comment]
according to my search console, it should work at least until Jul 9.

and all the plugins i have installed is assets, precache and twigcache.  
tried disabled them but still blanks.

I also wonder why...

![image](https://user-images.githubusercontent.com/4640483/125598396-d7c4b344-90cf-4739-90c6-e45243febb1c.png)
![image](https://user-images.githubusercontent.com/4640483/125598412-bbe23286-7be4-4ad3-9390-f2f73fabb948.png)

**Comment by CaiMiao** [comment]
it seems the problem of [tidyhtml](https://github.com/sourcesoldier/grav-plugin-tidyhtml/)
